# Generated by Django 5.2 on 2025-07-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_streaming', '0002_video_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status_emision',
            field=models.BooleanField(default='False'),
        ),
    ]
